from __future__ import annotations

from pathlib import Path

from docx import Document
from openpyxl import load_workbook

from tflshell.models.catalog import TFLCatalog
from tflshell.models.enums import Section, TFLType


DOCX_SECTION_HEADINGS = {
    "14.1": "14.1  Demographics and Baseline Characteristics",
    "14.2": "14.2  Efficacy Analysis",
    "14.3": "14.3  Safety Analysis",
    "14.4": "14.4  Special Assessments",
    "16.2": "16.2  Patient Data Listings",
}

SOP_TEMPLATE_TITLE = "Title: TFL Shell Template Usage and Management"
SOP_GOVERNED_SCOPE_TEXT = "14.1, 14.2, 14.3, 14.4, and 16.2"
SOP_ALIGNMENT_TEXT = (
    "All three deliverables must stay aligned on internal TFL ID, reviewer-facing display label, "
    "title, section, type, applicability, shell family, study phase scope, coverage summary, "
    "and versioning conventions."
)
SOP_QUALITY_GATES_TEXT = (
    "Automated quality gates should verify generation, catalog validation, and regression tests "
    "before release or controlled reuse."
)
SOP_REQUIRED_HEADINGS = {
    "1.  PURPOSE AND SCOPE",
    "2.  DEFINITIONS AND ABBREVIATIONS",
    "3.  RESPONSIBILITIES",
    "4.  PROCEDURE",
    "5.  REFERENCES",
    "6.  APPENDICES",
    "1.2  Scope",
    "4.1  Governed Deliverables",
    "4.6  TFL ID and File Naming Conventions",
    "4.7  Version Control and Change Management",
}
SOP_APPENDIX_HEADINGS = {
    "Appendix A  Companion Workbook",
    "Appendix B  Shell Output Notes",
}
SOP_HEADER_TABLE_LABELS = {"SOP No.", "Version", "Effective Date", "Department", "Classification"}

XLSX_EXPECTED_SHEETS = [
    "TOC_Master",
    "14.1_Demographics",
    "14.2_Efficacy",
    "14.3_Safety",
    "14.4_Special",
    "16.2_Listings",
    "Field_Definitions",
    "Usage_Guide",
    "Change_Log",
]
XLSX_CATALOG_COLUMNS = [
    "TFL ID",
    "Display Label",
    "Title",
    "Type",
    "Section",
    "Shell Family",
    "Study Phase Scope",
    "Coverage Summary",
    "Population",
    "Applicability",
    "Dataset Source",
    "Program Reference",
    "Dictionary / Standard",
    "Placeholder Style",
    "Footnotes",
    "Remarks",
]
XLSX_FIELD_DEFINITIONS = set(XLSX_CATALOG_COLUMNS)
XLSX_USAGE_TOPICS = {
    "Workbook purpose",
    "Scope",
    "Coverage metadata",
    "Applicability",
    "Placeholder convention",
    "Figures",
    "Ordering",
    "Word TOC",
    "Change management",
}
XLSX_CHANGE_LOG_COLUMNS = ["Date", "Version", "Scope", "Change Description", "Author"]

DOCX_TEMPLATE_HEADING1 = {"Table of Contents", "1.0  Introduction and Usage Notes"}
DOCX_TEMPLATE_INTRO_HEADINGS = {
    "1.1  Table and Listing Shell Conventions",
    "1.2  How to Use This Template",
    "1.3  Figure Shells",
}
DOCX_REQUIRED_INTRO_TEXT = [
    "Section 16.1 is intentionally excluded from this generator",
    "Controlled tables use `Group 1`, `Group 2`, and an optional separate ellipsis (`...`) expansion column",
    "must never be merged with Overall, HR, Total, or other analytic columns",
    "Figures retain simulated illustrations generated by matplotlib",
]
DOCX_EXPECTED_SECTION_COUNT = 1
DOCX_EXPECTED_PAGE_WIDTH_INCHES = 11.0
DOCX_EXPECTED_PAGE_HEIGHT_INCHES = 8.5
DOCX_EXPECTED_MARGIN_INCHES = 0.75


def _declared_reference(detail_keys: list[str], notes: list[str]) -> dict:
    return {
        "helper_module": str(Path(__file__).resolve()),
        "detail_keys": detail_keys,
        "notes": notes,
    }


def _expected_docx_items(scoped_catalog: TFLCatalog) -> list:
    ordered_items: list = []
    section_order = [
        Section.SEC_14_1,
        Section.SEC_14_2,
        Section.SEC_14_3,
        Section.SEC_14_4,
        Section.SEC_16_2,
    ]

    for section_enum in section_order:
        items = scoped_catalog.by_section(section_enum)
        tables = sorted((item for item in items if item.tfl_type == TFLType.TABLE), key=lambda item: item.sort_key)
        figures = sorted((item for item in items if item.tfl_type == TFLType.FIGURE), key=lambda item: item.sort_key)
        listings = sorted((item for item in items if item.tfl_type == TFLType.LISTING), key=lambda item: item.sort_key)

        if section_enum == Section.SEC_14_3:
            for sub_num in ("1", "2", "3", "4"):
                ordered_items.extend(item for item in tables if item.id.split(".")[-2] == sub_num)
                ordered_items.extend(item for item in figures if item.id.split(".")[-2] == sub_num)
            continue

        ordered_items.extend(tables)
        ordered_items.extend(figures)
        ordered_items.extend(listings)

    return ordered_items


def _collect_docx_paragraph_text(doc: Document, style_name: str | None = None) -> list[str]:
    return [
        paragraph.text.strip()
        for paragraph in doc.paragraphs
        if paragraph.text.strip() and (style_name is None or (paragraph.style is not None and paragraph.style.name == style_name))
    ]


def build_xlsx_master_sheet_contract(scoped_catalog: TFLCatalog, workbook_path: str) -> tuple[dict, dict]:
    workbook = load_workbook(workbook_path, read_only=True, data_only=True)
    sheet = workbook["TOC_Master"] if "TOC_Master" in workbook.sheetnames else None
    expected_items = scoped_catalog.all()
    expected_ids = [item.id for item in expected_items]
    expected_labels = [item.display_label for item in expected_items]
    expected_types = [item.tfl_type.value for item in expected_items]
    expected_sections = [item.section.number for item in expected_items]
    expected_shell_families = [item.shell_family_label for item in expected_items]
    expected_phase_scopes = [item.study_phase_scope_label for item in expected_items]
    expected_coverage = [item.coverage_summary_label for item in expected_items]
    expected_populations = [item.population for item in expected_items]
    expected_applicability = [item.applicability_label for item in expected_items]

    actual_ids: list[str] = []
    actual_labels: list[str] = []
    actual_types: list[str] = []
    actual_sections: list[str] = []
    actual_shell_families: list[str] = []
    actual_phase_scopes: list[str] = []
    actual_coverage: list[str] = []
    actual_populations: list[str] = []
    actual_applicability: list[str] = []

    if sheet is not None:
        header_row = next(sheet.iter_rows(min_row=1, max_row=1, values_only=True), ())
        header_index = {str(value): idx for idx, value in enumerate(header_row) if value is not None}

        id_idx = header_index.get("TFL ID", 0)
        label_idx = header_index.get("Display Label", 1)
        type_idx = header_index.get("Type")
        section_idx = header_index.get("Section")
        shell_family_idx = header_index.get("Shell Family")
        phase_scope_idx = header_index.get("Study Phase Scope")
        coverage_idx = header_index.get("Coverage Summary")
        population_idx = header_index.get("Population")
        applicability_idx = header_index.get("Applicability")

        for row in sheet.iter_rows(min_row=2, values_only=True):
            if not row or not row[id_idx]:
                continue
            actual_ids.append(str(row[id_idx]))
            actual_labels.append(str(row[label_idx]))
            actual_types.append("" if type_idx is None else str(row[type_idx]))
            actual_sections.append("" if section_idx is None else str(row[section_idx]))
            actual_shell_families.append("" if shell_family_idx is None else str(row[shell_family_idx]))
            actual_phase_scopes.append("" if phase_scope_idx is None else str(row[phase_scope_idx]))
            actual_coverage.append("" if coverage_idx is None else str(row[coverage_idx]))
            actual_populations.append("" if population_idx is None else str(row[population_idx]))
            actual_applicability.append("" if applicability_idx is None else str(row[applicability_idx]))
    workbook.close()

    checks = {
        "present": sheet is not None,
        "master_row_count": len(actual_ids),
        "expected_catalog_items": len(expected_ids),
        "ids_match_catalog": sheet is not None and actual_ids == expected_ids,
        "labels_match_catalog": sheet is not None and actual_labels == expected_labels,
        "types_match_catalog": sheet is not None and actual_types == expected_types,
        "sections_match_catalog": sheet is not None and actual_sections == expected_sections,
        "shell_families_match_catalog": sheet is not None and actual_shell_families == expected_shell_families,
        "study_phase_scope_match_catalog": sheet is not None and actual_phase_scopes == expected_phase_scopes,
        "coverage_summary_match_catalog": sheet is not None and actual_coverage == expected_coverage,
        "populations_match_catalog": sheet is not None and actual_populations == expected_populations,
        "applicability_match_catalog": sheet is not None and actual_applicability == expected_applicability,
    }
    reference = _declared_reference(
        detail_keys=[
            "TFL ID",
            "Display Label",
            "Type",
            "Section",
            "Shell Family",
            "Study Phase Scope",
            "Coverage Summary",
            "Population",
            "Applicability",
            "Row Count",
        ],
        notes=[
            "读取 TOC_Master 表头并按字段名映射，避免依赖固定列位置。",
            "当前用于声明 Skill 已引用的稳定 workbook 治理字段子集。",
        ],
    )
    return checks, reference


def build_xlsx_workbook_contract(scoped_catalog: TFLCatalog, workbook_path: str) -> tuple[dict, dict]:
    workbook = load_workbook(workbook_path, read_only=True, data_only=True)
    sheet_names = workbook.sheetnames
    expected_section_counts = {
        "TOC_Master": len(scoped_catalog.all()),
        "14.1_Demographics": len(scoped_catalog.by_section(Section.SEC_14_1)),
        "14.2_Efficacy": len(scoped_catalog.by_section(Section.SEC_14_2)),
        "14.3_Safety": len(scoped_catalog.by_section(Section.SEC_14_3)),
        "14.4_Special": len(scoped_catalog.by_section(Section.SEC_14_4)),
        "16.2_Listings": len(scoped_catalog.by_section(Section.SEC_16_2)),
    }

    catalog_headers_match = True
    section_row_counts_match = True
    for sheet_name, expected_count in expected_section_counts.items():
        if sheet_name not in workbook:
            catalog_headers_match = False
            section_row_counts_match = False
            continue
        sheet = workbook[sheet_name]
        header_row = next(sheet.iter_rows(min_row=1, max_row=1, values_only=True), ())
        headers = [value for value in header_row if value is not None]
        catalog_headers_match = catalog_headers_match and headers == XLSX_CATALOG_COLUMNS
        actual_count = sum(1 for row in sheet.iter_rows(min_row=2, values_only=True) if row and row[0])
        section_row_counts_match = section_row_counts_match and actual_count == expected_count

    field_definitions_present = False
    if "Field_Definitions" in workbook:
        field_sheet = workbook["Field_Definitions"]
        field_names = {
            row[0]
            for row in field_sheet.iter_rows(min_row=2, values_only=True)
            if row and row[0]
        }
        field_definitions_present = XLSX_FIELD_DEFINITIONS.issubset(field_names)

    usage_topics_present = False
    usage_placeholder_contract_present = False
    if "Usage_Guide" in workbook:
        usage_sheet = workbook["Usage_Guide"]
        usage_rows = {
            row[0]: row[1]
            for row in usage_sheet.iter_rows(min_row=2, values_only=True)
            if row and row[0]
        }
        usage_topics_present = XLSX_USAGE_TOPICS.issubset(set(usage_rows))
        placeholder_text = usage_rows.get("Placeholder convention", "")
        usage_placeholder_contract_present = (
            "Group 1, Group 2" in placeholder_text
            and "ellipsis (...)" in placeholder_text
            and "must not be merged with Overall, Total, HR" in placeholder_text
        )

    change_log_columns_match = False
    if "Change_Log" in workbook:
        change_sheet = workbook["Change_Log"]
        header_row = next(change_sheet.iter_rows(min_row=1, max_row=1, values_only=True), ())
        change_log_columns_match = [value for value in header_row if value is not None] == XLSX_CHANGE_LOG_COLUMNS

    workbook.close()
    checks = {
        "present": Path(workbook_path).exists(),
        "sheet_names": sheet_names,
        "sheet_names_match_contract": sheet_names == XLSX_EXPECTED_SHEETS,
        "catalog_sheet_headers_match_contract": catalog_headers_match,
        "section_sheet_row_counts_match_catalog": section_row_counts_match,
        "field_definitions_cover_catalog_columns": field_definitions_present,
        "usage_guide_topics_present": usage_topics_present,
        "usage_placeholder_contract_present": usage_placeholder_contract_present,
        "change_log_columns_match_contract": change_log_columns_match,
    }
    reference = _declared_reference(
        detail_keys=[
            "Workbook Sheets",
            "Catalog Sheet Columns",
            "Section Sheet Row Counts",
            "Field Definitions",
            "Usage Guide",
            "Change Log",
        ],
        notes=[
            "用于声明 Skill 已引用完整 XLSX workbook 结构 contract。",
            "该 contract 覆盖 sheet 名、catalog 字段、使用说明与变更记录结构。",
        ],
    )
    return checks, reference


def build_docx_shell_contract(scoped_catalog: TFLCatalog, docx_path: str) -> tuple[dict, dict]:
    doc = Document(docx_path)
    expected_items = _expected_docx_items(scoped_catalog)
    expected_heading_labels = [f"{item.display_label}  {item.title}" for item in expected_items]
    expected_display_labels = [item.display_label for item in expected_items]
    expected_titles = [item.title for item in expected_items]
    expected_populations = [f"Analysis Set: {item.population}" for item in expected_items]
    expected_section_headings = {
        DOCX_SECTION_HEADINGS[item.section.number]
        for item in expected_items
        if item.section.number in DOCX_SECTION_HEADINGS
    }

    all_paragraphs = _collect_docx_paragraph_text(doc)
    heading4_paragraphs = _collect_docx_paragraph_text(doc, "Heading 4")
    heading2_paragraphs = set(_collect_docx_paragraph_text(doc, "Heading 2"))
    display_label_lines = [text for text in all_paragraphs if text in expected_display_labels]
    title_lines = [text for text in all_paragraphs if text in expected_titles]
    analysis_set_lines = [text for text in all_paragraphs if text.startswith("Analysis Set: ")]
    protocol_lines = [text for text in all_paragraphs if text.startswith("Protocol: ")]
    sponsor_lines = [text for text in all_paragraphs if text.startswith("Sponsor: ")]

    checks = {
        "present": True,
        "heading_count": len(heading4_paragraphs),
        "expected_catalog_items": len(expected_heading_labels),
        "heading_count_matches_catalog": len(heading4_paragraphs) == len(expected_heading_labels),
        "heading_labels_match_catalog": heading4_paragraphs == expected_heading_labels,
        "section_headings_cover_recommendation": expected_section_headings.issubset(heading2_paragraphs),
        "display_label_lines_match_catalog": display_label_lines == expected_display_labels,
        "title_lines_match_catalog": title_lines == expected_titles,
        "analysis_set_lines_match_catalog": analysis_set_lines == expected_populations,
        "protocol_lines_present": len(protocol_lines) == len(expected_items),
        "sponsor_lines_present": len(sponsor_lines) == len(expected_items),
    }
    reference = _declared_reference(
        detail_keys=[
            "Heading 4",
            "Section Heading",
            "Display Label",
            "Title",
            "Analysis Set",
            "Protocol",
            "Sponsor",
        ],
        notes=[
            "按 DOCX 实际生成顺序构造期望项，兼容 14.3 子分节重排。",
            "用于声明 Skill 已引用的稳定 header block 与 heading contract。",
        ],
    )
    return checks, reference


def build_docx_layout_contract(scoped_catalog: TFLCatalog, docx_path: str) -> tuple[dict, dict]:
    doc = Document(docx_path)
    section = doc.sections[0]
    all_paragraphs = _collect_docx_paragraph_text(doc)
    heading1 = set(_collect_docx_paragraph_text(doc, "Heading 1"))
    heading2 = set(_collect_docx_paragraph_text(doc, "Heading 2"))
    joined_text = "\n".join(all_paragraphs)
    expected_body_table_count = len([
        item for item in scoped_catalog.all()
        if item.tfl_type in (TFLType.TABLE, TFLType.LISTING)
    ])
    first_table_headers: list[str] = []
    if doc.tables:
        first_table_headers = [cell.text.strip() for cell in doc.tables[0].rows[0].cells]

    checks = {
        "present": Path(docx_path).exists(),
        "section_count": len(doc.sections),
        "section_count_matches_contract": len(doc.sections) == DOCX_EXPECTED_SECTION_COUNT,
        "page_size_matches_landscape_letter": (
            round(section.page_width.inches, 1) == DOCX_EXPECTED_PAGE_WIDTH_INCHES
            and round(section.page_height.inches, 1) == DOCX_EXPECTED_PAGE_HEIGHT_INCHES
        ),
        "margins_match_contract": all(
            round(value.inches, 2) == DOCX_EXPECTED_MARGIN_INCHES
            for value in (
                section.top_margin,
                section.bottom_margin,
                section.left_margin,
                section.right_margin,
            )
        ),
        "heading1_contract_present": DOCX_TEMPLATE_HEADING1.issubset(heading1),
        "intro_heading_contract_present": DOCX_TEMPLATE_INTRO_HEADINGS.issubset(heading2),
        "required_intro_text_present": all(text in joined_text for text in DOCX_REQUIRED_INTRO_TEXT),
        "body_table_count": len(doc.tables),
        "expected_body_table_count": expected_body_table_count,
        "body_table_count_matches_table_and_listing_shells": len(doc.tables) == expected_body_table_count,
        "first_table_uses_group_headers": any("Group 1" in value for value in first_table_headers)
        and any("Group 2" in value for value in first_table_headers),
    }
    reference = _declared_reference(
        detail_keys=[
            "Landscape Letter Page Setup",
            "Margins",
            "Introduction Headings",
            "Usage Notes",
            "Body Table Count",
            "Group Headers",
        ],
        notes=[
            "用于声明 Skill 已引用 DOCX 主模板的可观察 layout contract。",
            "该 contract 覆盖页面设置、说明文本、表/listing 表格数量与受控组别表头。",
        ],
    )
    return checks, reference


def build_sop_contract(sop_path: str) -> tuple[dict, dict]:
    sop_doc = Document(sop_path)
    paragraph_texts = _collect_docx_paragraph_text(sop_doc)
    paragraph_set = set(paragraph_texts)
    sop_text = "\n".join(paragraph_texts)

    header_table_labels = set()
    classification_confidential_present = False
    if sop_doc.tables:
        for row in sop_doc.tables[0].rows:
            if len(row.cells) < 2:
                continue
            label = row.cells[0].text.strip()
            value = row.cells[1].text.strip()
            if label:
                header_table_labels.add(label)
            if label == "Classification" and value == "CONFIDENTIAL":
                classification_confidential_present = True

    checks = {
        "present": True,
        "title_matches_template": SOP_TEMPLATE_TITLE in sop_text,
        "scope_matches_governed_sections": SOP_GOVERNED_SCOPE_TEXT in sop_text,
        "mentions_cross_output_alignment": SOP_ALIGNMENT_TEXT in sop_text,
        "mentions_quality_gates": SOP_QUALITY_GATES_TEXT in sop_text,
        "header_table_labels_present": SOP_HEADER_TABLE_LABELS.issubset(header_table_labels),
        "classification_confidential_present": classification_confidential_present,
        "required_heading_structure_present": SOP_REQUIRED_HEADINGS.issubset(paragraph_set),
        "appendix_headings_present": SOP_APPENDIX_HEADINGS.issubset(paragraph_set),
    }
    reference = _declared_reference(
        detail_keys=[
            "Title",
            "Scope",
            "Cross-Output Alignment",
            "Quality Gates",
            "Classification",
            "Appendix A",
            "Appendix B",
        ],
        notes=[
            "用于声明 Skill 已引用的稳定 SOP 治理语言与结构 contract。",
            "当前聚焦头表、受控 scope、关键 heading 与 appendix 层级。",
        ],
    )
    return checks, reference
